#!/usr/bin/env python3
"""
Build one hero film per account from a spec. 32 seconds, four beats, one through-line.

    python3 build_vsl.py --run ~/path/to/client-run

The creative call is in ../knowledge-base/hero-film-format.md and is the same for every
account:
a single rule enters as the underline of a line the account published itself, becomes
the dated axis, forks into the two layers, then thickens into the money. Blue is
withheld until the last bar. Nothing is padded to fill a slot, so no frame holds still.

Every figure traces to the run's own evidence and to the filing named in each cite.
Arithmetic is labelled as arithmetic on the frame that shows it.
"""
import argparse, html, json, sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from runpaths import Run, add_run_arg

def e(s): return html.escape(s, quote=False)

# the client's four films live in <run>/04-pages/vsl/films.json, not in this file
TEMPLATE = r"""<!doctype html><html lang="en-GB"><head><meta charset="utf-8">
<title>{NAME} — hero film</title>
<!--
  Generated by build_vsl.py. Do not hand edit: edit the spec and rebuild.
  32.0s, four beats, every handover overlapped. Deterministic window.seek(p), p 0..1.
  Creative call: VSL-CREATIVE-BRIEF.md. Figures: content_<account>.py and the cites on screen.
-->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>
:root{{--ink:{INK};--blue:{ACCENT};--wash:{WASH};--muted:{MUTED};--rule:{RULE}}}
*{{margin:0;padding:0;box-sizing:border-box}}
html,body{{width:1920px;height:1080px;overflow:hidden}}
body{{background:#fff;font-family:Inter,system-ui,sans-serif;color:var(--ink);position:relative}}
.topbar{{position:absolute;top:0;left:0;right:0;height:104px;display:flex;align-items:center;
 justify-content:space-between;padding:0 160px;border-bottom:1px solid var(--rule);z-index:9}}
.gc{{font-size:32px;font-weight:800;letter-spacing:-.03em}}
.prep{{font-size:20px;color:var(--muted)}}
.prep b{{color:var(--ink);font-weight:700}}
.prog{{position:absolute;left:0;bottom:0;height:6px;background:var(--rule);width:0;z-index:9}}
.stage{{position:absolute;inset:0;z-index:1}}
.abs{{position:absolute}}
#ruleA,#ruleB{{position:absolute;height:3px;background:var(--ink);border-radius:2px;z-index:4}}
#box{{position:absolute;z-index:5;border:3px solid var(--ink);border-radius:6px;background:transparent}}
.hl{{position:absolute;left:160px;font-weight:700;letter-spacing:-.034em;line-height:1.04;max-width:1600px}}
.sub{{position:absolute;left:160px;font-size:28px;color:var(--muted);line-height:1.42}}
.micro{{position:absolute;left:160px;font-size:21px;color:var(--muted);line-height:1.42}}
#quote{{position:absolute;left:160px;top:392px;width:1640px;font-size:42px;line-height:60px;font-weight:500}}
#mk{{font-weight:700}}
.tick{{position:absolute;width:3px;background:var(--ink);border-radius:2px}}
.tlab{{position:absolute;font-size:24px;font-weight:600;color:var(--muted);white-space:nowrap}}
.tlab b{{display:block;font-size:26px;font-weight:700;color:var(--ink);margin-bottom:4px}}
.lane .k{{font-size:19px;font-weight:700;letter-spacing:.15em;text-transform:uppercase;color:var(--muted)}}
.lane .v{{margin-top:14px;font-size:56px;font-weight:700;letter-spacing:-.03em;line-height:1.06}}
.lane .n{{margin-top:14px;font-size:26px;color:var(--muted)}}
.barlab{{position:absolute;left:160px;width:1560px;display:flex;justify-content:space-between;align-items:baseline}}
.barlab span{{font-size:26px;color:var(--muted)}}
.barlab b{{font-size:52px;font-weight:700;letter-spacing:-.025em}}
#sliver{{position:absolute;background:var(--blue);border-radius:3px}}
#cta{{position:absolute;left:160px;font-size:34px;font-weight:700;letter-spacing:-.02em}}
</style></head><body>

<div class="topbar"><span class="gc">{VENDOR}</span>
 <span class="prep">Prepared for <b>{NAME}</b></span></div>
<div class="prog" id="pg"></div>

<div class="stage">
 <div class="hl" id="h1" style="top:196px;font-size:{S1}px">{H1}</div>
 <div class="hl" id="h2" style="top:196px;font-size:{S2}px">{H2}</div>
 <div class="hl" id="h3" style="top:150px;font-size:{S3}px">{H3}</div>
 <div class="hl" id="h4" style="top:196px;font-size:{S4}px">{H4}</div>

 <div id="quote">{QUOTE}</div>
 <div class="micro" id="cite" style="top:672px">{CITE}</div>

 <div class="sub" id="s2" style="top:320px">{SUB2}</div>
{TICKS}
{TLABS}

 <div class="lane abs" id="lnA" style="left:160px;top:250px;width:1560px">
  <div class="k">{A0}</div><div class="v">{A1}</div><div class="n">{A2}</div></div>
 <div class="lane abs" id="lnB" style="left:160px;top:632px;width:1560px">
  <div class="k">{B0}</div><div class="v">{B1}</div><div class="n">{B2}</div></div>

 <div class="barlab" id="bl1" style="top:388px"><span>{L1}</span><b id="c1">{PRE}0{SUF}</b></div>
 <div class="barlab" id="bl2" style="top:598px"><span>{L2}</span><b id="c2" style="color:{ACCENT}">{V2}</b></div>
 <div id="sliver" style="left:160px;top:680px;height:64px;width:0"></div>
 <div class="micro" id="arith" style="top:786px">{ARITH}</div>
 <div id="cta" style="top:896px">{CTA} &rarr;</div>
 <div id="tail" style="position:absolute;top:952px;height:4px;background:{ACCENT};border-radius:2px;left:1720px;width:0"></div>

 <div id="ruleA"></div><div id="ruleB"></div><div id="box"></div>
</div>

<script>
window.DURATION = 32.0;                 // seconds. the renderer reads this.
var SPEC = {SPEC};
var AX0 = 160, AX1 = 1720, AXW = AX1 - AX0;
var STOPS = SPEC.stops.map(function(s){{return s[0];}});
var MK = null;

function cl(t){{return t<0?0:t>1?1:t}}
function ease(t){{return 1-Math.pow(1-t,3)}}
function easeIO(t){{return t<0.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2}}
function lerp(a,b,t){{return a+(b-a)*t}}
function px(v){{return v.toFixed(2)+'px'}}
function o(el,v){{el.style.opacity=v}}
function E(id){{return document.getElementById(id)}}

window.seek = function(p){{
  var T = p * window.DURATION;
  function s(a,b){{return cl((T-a)/(b-a));}}
  // measured every frame, not cached: seek(0) runs before the webfont lands
  var r = E('mk').getBoundingClientRect();
  MK = {{x:r.x, y:r.y, w:r.width, h:r.height, uy:r.y+r.height+8}};

  E('pg').style.width = (p*100)+'%';

  // ================= BEAT 1 : 0.0 -> 8.6 =================
  var wipe = ease(s(0.6, 5.0));
  var out1 = ease(s(7.2, 8.6));
  o(E('h1'), ease(s(0.15, 1.1)) * (1-out1));
  E('h1').style.transform = 'translateY('+px((1-ease(s(0.15,1.1)))*20 - out1*26)+')';
  o(E('quote'), (wipe>0?1:0) * (1-out1));
  E('quote').style.clipPath = 'inset(0 '+((1-wipe)*100).toFixed(2)+'% 0 0)';
  E('quote').style.transform = 'translateY('+px(-out1*26)+')';
  E('quote').style.color = out1 > 0 ? 'rgba(22,22,63,'+(1-out1*0.55).toFixed(3)+')' : '{INK}';
  o(E('cite'), ease(s(5.2, 6.2)) * (1-out1));

  // ================= BEAT 2 : 7.2 -> 15.8 =================
  var in2 = ease(s(7.6, 8.6)), out2 = ease(s(14.4, 15.8));
  o(E('h2'), in2 * (1-out2));
  E('h2').style.transform = 'translateY('+px((1-in2)*22 - out2*26)+')';
  o(E('s2'), ease(s(8.4, 9.4)) * (1-out2));

  // ================= BEAT 3 : 14.4 -> 24.0 =================
  var in3 = ease(s(14.9, 16.0)), out3 = ease(s(22.6, 24.0));
  o(E('h3'), in3 * (1-out3));
  E('h3').style.transform = 'translateY('+px((1-in3)*22 - out3*26)+')';
  var lA = ease(s(15.6, 16.8)), lB = ease(s(17.4, 18.6));
  var dimA = ease(s(20.4, 22.4));
  o(E('lnA'), lA * (1 - out3) * (1 - dimA*0.72));
  E('lnA').style.transform = 'translateY('+px((1-lA)*18 - out3*22)+')';
  o(E('lnB'), lB * (1-out3));
  E('lnB').style.transform = 'translateY('+px((1-lB)*18 - out3*22)+')';

  // ================= BEAT 4 : 23.0 -> 32.0 =================
  var in4 = ease(s(23.4, 24.6));
  o(E('h4'), in4);
  E('h4').style.transform = 'translateY('+px((1-in4)*22)+')';
  o(E('bl1'), ease(s(24.6, 25.4)));
  var grow = ease(s(25.0, 28.0));
  E('c1').textContent = SPEC.pre + (SPEC.to*grow).toFixed(SPEC.dp) + SPEC.suf;
  var snap = cl((T-28.4)/0.134);                    // four frames. the film pays off here
  E('sliver').style.width = px(snap * AXW * SPEC.ratio);
  o(E('bl2'), cl((T-28.4)/0.30));
  o(E('arith'), ease(s(28.9, 30.0)));
  var cta = ease(s(29.8, 30.9));
  o(E('cta'), cta);
  E('cta').style.transform = 'translateY('+px((1-cta)*16)+')';
  var tail = ease(s(30.3, 32.0));
  E('tail').style.left = px(lerp(AX1, AX0, tail));
  E('tail').style.width = px(AX1 - lerp(AX1, AX0, tail));
  E('pg').style.background = snap > 0 ? '{ACCENT}' : '{RULE}';

  // ================= THE THROUGH-LINE =================
  var rx0, rx1, ry, rh = 3, rop = 1;
  var underW = MK.w * ease(s(0.9, 5.2));
  if (T < 7.2) {{                                    // job 1: the underline chasing the wipe
    rx0 = MK.x; rx1 = MK.x + underW; ry = MK.uy;
  }} else if (T < 14.4) {{                            // job 2: it stretches into the axis
    var g = easeIO(s(7.2, 11.4));
    rx0 = lerp(MK.x, AX0, g); rx1 = lerp(MK.x + MK.w, AX1, g); ry = lerp(MK.uy, 600, g);
  }} else if (T < 23.0) {{                            // job 3: it forks into two layers
    var f = easeIO(s(14.6, 16.6));
    rx0 = AX0; rx1 = AX1; ry = lerp(600, 410, f);
  }} else {{                                          // job 4: the upper layer lets go
    rx0 = AX0; rx1 = AX1; ry = 410; rop = 1 - ease(s(23.2, 24.6));
  }}
  var A = E('ruleA');
  A.style.left = px(rx0); A.style.width = px(Math.max(0, rx1-rx0));
  A.style.top = px(ry); A.style.height = px(rh); A.style.background = '{INK}'; o(A, rop);

  var B = E('ruleB'), bx0 = rx0, bx1 = rx1, by = ry, bh = 3;
  if (T >= 14.4 && T < 23.0) {{
    by = lerp(600, 790, easeIO(s(14.6, 16.6)));
  }} else if (T >= 23.0) {{
    var m = easeIO(s(23.2, 25.0));                  // it rises, thickens, and gathers to nothing
    by = lerp(790, 460, m); bh = lerp(3, 64, m);
    bx1 = AX0 + (m < 1 ? AXW * (1-m) : AXW * grow); // then sweeps back out as the money
  }}
  B.style.left = px(bx0); B.style.width = px(Math.max(0, bx1-bx0));
  B.style.top = px(by); B.style.height = px(bh); o(B, 1);

  // ================= THE MARKER =================
  // the box that lands on the line they published becomes the date, the layer, then the money
  var X = E('box'), bxx, bxy, bxw, bxh, bxo = 1;
  var mx = AX0 + AXW*SPEC.marker;
  if (T < 7.2) {{
    bxw = MK.w + 18; bxh = MK.h + 10; bxx = MK.x - 9; bxy = MK.y - 5; bxo = ease(s(3.4, 4.6));
  }} else if (T < 14.4) {{
    var g2 = easeIO(s(8.2, 11.8));
    bxw = lerp(MK.w+18, 26, g2); bxh = lerp(MK.h+10, 26, g2);
    bxx = lerp(MK.x-9, mx-13, g2); bxy = lerp(MK.y-5, 587, g2);
  }} else if (T < 23.0) {{
    var g3 = easeIO(s(14.6, 17.0));
    bxw = 26; bxh = 26;
    bxx = lerp(mx-13, AX0 + AXW*0.34, g3); bxy = lerp(587, 777, g3);
  }} else {{
    var g4 = easeIO(s(23.2, 25.4));
    bxw = lerp(26, Math.max(10, AXW*SPEC.ratio), g4); bxh = lerp(26, 64, g4);
    bxx = lerp(AX0 + AXW*0.34, AX0, g4); bxy = lerp(777, 680, g4);
    if (snap > 0){{ bxo = 0; }}
  }}
  X.style.left = px(bxx); X.style.top = px(bxy); X.style.width = px(bxw); X.style.height = px(bxh);
  o(X, bxo);

  // ================= AXIS FURNITURE =================
  var reach = rx1;                                   // ticks rise as the rule passes them
  for (var i=0;i<STOPS.length;i++){{
    var tx = AX0 + AXW*STOPS[i], above = SPEC.stops[i][3] === 'above';
    var v = (T>=7.2 && T<15.8) ? cl((reach - tx)/60) * (1-out2) : 0;
    var k = E('k'+i);
    k.style.left = px(tx-1.5); k.style.top = px(600 - (above?26:0));
    k.style.height = px(v * (above?52:26)); o(k, v);
    var l = E('l'+i), side = SPEC.stops[i][3];
    if (side === 'below' && STOPS[i] === 0) l.style.left = px(tx);
    else if (side === 'right') {{ l.style.left = px(tx-460); l.style.width = '460px'; }}
    else l.style.left = px(tx - 74);
    o(l, above ? ease(cl((v-0.55)/0.45)) * (1-out2) : v * (1-out2));
    l.style.transform = 'translateY('+px((1-v)*10)+')';
  }}
}};
window.seek(0);
</script></body></html>
"""

def fit(text, base, cap=1600):
    """Headlines are one line. Shrink the type rather than let it wrap."""
    n = len(text)
    if n <= 26: return base
    if n <= 32: return base - 6
    if n <= 40: return base - 14
    return base - 22

BRAND = {}

def load_brand(run):
    """Le vendeur et sa palette vivent dans pages.json, jamais dans ce fichier."""
    p = run.pages / "pages.json"
    if p.exists():
        c = json.loads(p.read_text(encoding="utf-8"))
        b = c.get("brand", {})
        return {"vendor": c.get("vendor", {}).get("name", "Vendor"),
                "cta": c.get("film_cta") or c.get("vendor", {}).get("cta") or "See what it is worth",
                "ink": b.get("ink", "#0F1521"), "accent": b.get("blue", "#1A88FF"),
                "wash": b.get("wash", "#F4F7FB"), "muted": b.get("muted", "#5B6675"),
                "rule": b.get("rule", "#E3E9F1")}
    raise SystemExit("pages.json absent: le film ne connait ni le vendeur ni sa palette")


def build(slug, a, outdir, today):
    b1, b2, b3, b4 = a["b1"], a["b2"], a["b3"], a["b4"]
    op, cp = ("&ldquo;", "&rdquo;") if b1["quoted"] else ("", "")
    quote = op + "<br>\n  ".join(e(x) for x in b1["lines"]) + "<br>\n  " \
            + '<span id="mk">' + e(b1["mark"]) + "</span>" + e(b1["tailtext"]) + cp

    ticks, tlabs = [], []
    for i, (pos, title, sub, side) in enumerate(b2["stops"]):
        if b2.get("days_to") and "{days}" in sub:
            d = (date.fromisoformat(b2["days_to"]) - date.fromisoformat(today)).days
            sub = sub.replace("{days}", str(d))
        ticks.append(' <div class="tick" id="k%d"></div>' % i)
        top = 474 if side == "above" else 640
        align = ';text-align:right' if side == "right" else ''
        inner = ('<b>%s</b>%s' % (e(title), e(sub))) if title else e(sub)
        tlabs.append(' <div class="tlab" id="l%d" style="top:%dpx%s">%s</div>' % (i, top, align, inner))

    spec = {"stops": b2["stops"], "marker": b2["marker"], "ratio": b4["ratio"],
            "to": b4["to"], "dp": b4["dp"], "pre": b4["pre"], "suf": b4["suf"]}

    out = TEMPLATE.format(
        NAME=e(a["name"]), SPEC=json.dumps(spec, ensure_ascii=False),
        VENDOR=e(BRAND["vendor"]), CTA=e(BRAND["cta"]),
        INK=BRAND["ink"], ACCENT=BRAND["accent"], WASH=BRAND["wash"],
        MUTED=BRAND["muted"], RULE=BRAND["rule"],
        H1=e(b1["head"]), H2=e(b2["head"]), H3=e(b3["head"]), H4=e(b4["head"]),
        S1=fit(b1["head"], 84), S2=fit(b2["head"], 84), S3=fit(b3["head"], 76), S4=fit(b4["head"], 84),
        QUOTE=quote, CITE=e(b1["cite"]), SUB2=b2["sub"],
        TICKS="\n".join(ticks), TLABS="\n".join(tlabs),
        A0=e(b3["a"][0]), A1=e(b3["a"][1]), A2=e(b3["a"][2]),
        B0=e(b3["b"][0]), B1=e(b3["b"][1]), B2=e(b3["b"][2]),
        L1=e(b4["l1"]), L2=e(b4["l2"]), V2=e(b4["v2"]),
        PRE=b4["pre"], SUF=b4["suf"],
        ARITH="<br>".join(e(x) for x in b4["arith"]),
    )
    p = outdir / (slug + "-vsl.html")
    p.write_text(out, encoding="utf-8")
    print("  %-16s %6d bytes  ratio %.3f" % (slug, len(out), b4["ratio"]))

if __name__ == "__main__":
    ap = add_run_arg(argparse.ArgumentParser(description="build one 32s hero film per account"))
    ap.add_argument("--today", default=date.today().isoformat(),
                    help="anchors any 'in N days' counter. Defaults to today, so a re-render is never stale")
    ap.add_argument("--only", default="", help="one slug, instead of all of them")
    a = ap.parse_args()
    run = Run(a.run)
    run.vsl.mkdir(parents=True, exist_ok=True)
    BRAND.update(load_brand(run))
    spec_path = run.need(run.vsl / "films.json")
    films = json.loads(spec_path.read_text(encoding="utf-8"))
    if a.only:
        films = {a.only: films[a.only]}
    print("hero films, 32.0s each, from %s" % spec_path)
    for slug, acct in films.items():
        build(slug, acct, run.vsl, a.today)
